name: Build Dev Version

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/dev.yml'
  pull_request:
    branches:
      - dev
    paths:
      - '.github/workflows/dev.yml'



jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dev/requirements.txt
          pip install pyinstaller

      - name: Build EXE with custom name
        run: |
          pyinstaller main.py -D --icon=bread.ico --name BakeLauncher

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: BakeLauncher-Dev-KB111924.Windows
          path: dist/

  macos-build:
    runs-on: 	macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dev/requirements.txt
          pip install pyinstaller

      - name: Build APP with custom name and x86-64 target
        run: |
          pyinstaller main.py -D --icon=bread.ico --name BakeLauncher

      - name: Upload APP
        uses: actions/upload-artifact@v4
        with:
          name: BakeLauncher-Dev-KB111924.macOS
          path: dist/

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dev/requirements.txt
          pip install pyinstaller

      - name: Build Linux binary with custom name
        run: |
          pyinstaller main.py -D --icon=bread.ico --name BakeLauncher

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: BakeLauncher-Dev-KB111924.Linux
          path: dist/
