name: Build Dev Version

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/dev.yml'
  pull_request:
    branches:
      - dev
    paths:
      - '.github/workflows/dev.yml'

permissions:
  contents: write  # Grant write permissions to content (push tags and create releases)

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dev/requirements.txt
          pip install pyinstaller

      - name: BakeLauncher Dev Version For Windows
        run: |
          pyinstaller main.py -D --icon=bread.ico --name BakeLauncher

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: BakeLauncher-Dev-KF112324.Windows
          path: dist/

  macos-build:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dev/requirements.txt
          pip install pyinstaller

      - name: BakeLauncher Dev Version For macOS(x86-64)
        run: |
          pyinstaller main.py -D --icon=bread.ico --name BakeLauncher

      - name: Upload APP
        uses: actions/upload-artifact@v4
        with:
          name: BakeLauncher-Dev-KF112324.macOS
          path: dist/

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dev/requirements.txt
          pip install pyinstaller

      - name: BakeLauncher Dev Version For Linux
        run: |
          pyinstaller main.py -D --icon=bread.ico --name BakeLauncher

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: BakeLauncher-Dev-KF112324.Linux
          path: dist/

  create-latest-tag:
    runs-on: ubuntu-latest
    needs: [windows-build, macos-build, linux-build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create and push 'Latest' tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -f Latest
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} Latest --force

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: BakeLauncher-Dev-KF112324.Linux

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: BakeLauncher-Dev-KF112324.Windows

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: BakeLauncher-Dev-KF112324.macOS

      - name: Prepare Dist Directory
        run: |
          mkdir -p dist
          mv BakeLauncher-Dev-KF112324.* dist/

      - name: Verify Dist Contents
        run: |
          echo "Listing files in 'dist' directory:"
          ls -la dist/

      - name: Create Release for 'Latest' Tag and Upload Artifacts
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Latest
          files: |
            dist/*
          make_latest: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
