name: Build EXE and APP

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dev/requirements.txt
          pip install pyinstaller

      - name: Build EXE with custom name
        run: |
          pyinstaller __main__.py -D --icon=bread.ico --name BakeLauncher

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: BakeLauncher-Dev-JB011024.Windows
          path: dist/

  macos-build:
    runs-on: 	macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dev\requirements.txt
          pip install pyinstaller

      - name: Build APP with custom name and x86-64 target
        run: |
          pyinstaller __main__.py -D --icon=bread.ico --name BakeLauncher

      - name: Upload APP
        uses: actions/upload-artifact@v4
        with:
          name: BakeLauncher-Dev-JB011024.macOS
          path: dist/
