name: Build EXE and APP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller __main__.py -D --icon=bread.ico

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: BakeLauncher-0.7.Windows.zip
          path: dist/

  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build APP
        run: |
          pyinstaller __main__.py -D --icon=bread.ico

      - name: Upload APP
        uses: actions/upload-artifact@v4
        with:
          name: BakeLauncher-0.7.macOS.zip
          path: dist/
