name: Build Executables

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Windows Executable
      run: |
        pyinstaller __main__.py
        

    - name: List dist folder contents (for debugging)
      run: |
        dir dist

    - name: Upload exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: BakeLauncher-Windows(0.7RC)
        path: dist/__main__.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build macOS Executable
      run: |
        pyinstaller --windowed __main__.py

    - name: List dist folder contents (for debugging)
      run: |
        ls dist

    - name: Upload app artifact
      uses: actions/upload-artifact@v3
      with:
        name: BakeLauncher-macOS(0.7RC)
        path: dist/__main__.app
